name: linux
on:
  push:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".github/workflows/windows*.yml"
      - ".github/workflows/macos*.yml"
  pull_request:
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - ".github/workflows/windows*.yml"
      - ".github/workflows/macos*.yml"
  workflow_dispatch:

jobs:
  build_package_upload:
    env:
      APP_NAME: qt-screen-HiDPI-test-1

      LINUXDEPLOYQT_URL: "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"

      MAKE_INSTALL_DIR_PATH: ${{ github.workspace }}/${{ github.run_id }}/build
      PACKAGE_DIR_PATH: ${{ github.workspace }}/${{ github.run_id }}/package

      LINUXDEPLOYQT_PATH: "${{ github.workspace }}/linuxdeployqt.AppImage"

    runs-on: ubuntu-16.04
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        qt_ver: [5.15.2]
        experimental: [false]
    steps:
      - name: What time?
        id: my_luminous_watch
        uses: 1466587594/get-current-time@v2
        with:
          format: "YYYYMMDDHHmmss"

      - uses: actions/checkout@v2

      - name: Create directories
        run: |
          mkdir -p '${{ env.MAKE_INSTALL_DIR_PATH }}'
          mkdir -p '${{ env.PACKAGE_DIR_PATH }}'

      - run: |
          sudo apt-get update

      - run: |
          # https://doc.qt.io/qt-5/linux.html#debian-ubuntu-apt-get
          sudo apt install -y libgl1-mesa-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.qt_ver }}
          target: desktop

      - name: Find Qt 5
        if: ${{ startsWith(matrix.qt_ver, '5') }}
        run: |
          echo 'Qt5_DIR = ${{ env.Qt5_DIR }}'
          echo 'Qt_DIR=${{ env.Qt5_DIR }}' >> ${GITHUB_ENV}

      - name: Configure Qt env
        run: |
          echo '${{ env.Qt_DIR }}/bin' >> ${GITHUB_PATH}

      - name: Test Qt & env
        run: |
          echo ${PATH}

          which 'qmake'

          qmake '-query'

      - name: Build ${{ steps.getGitInfo.outputs.versionNumber }}+${{ steps.getGitInfo.outputs.gitCommitSha1 }}
        run: |
          qmake \
            '-makefile' \
            '-o' 'Makefile' \
            '-spec' 'linux-g++' \
            '-after' \
            'TARGET=${{ env.APP_NAME }}' \
            'CONFIG+=release' \
            '${{ github.workspace }}'

          make

          make install INSTALL_ROOT='${{ env.MAKE_INSTALL_DIR_PATH }}'

          du -ah '${{ env.MAKE_INSTALL_DIR_PATH }}'

      - name: Prepare for packaging
        run: |
          wget '${{ env.LINUXDEPLOYQT_URL }}' -O '${{ env.LINUXDEPLOYQT_PATH }}'
          chmod u+x '${{ env.LINUXDEPLOYQT_PATH }}'

          # I stole it.
          mkdir -p '${{ env.MAKE_INSTALL_DIR_PATH }}/usr/share/icons/scalable/apps'
          wget \
            'https://raw.githubusercontent.com/probonopd/linuxdeployqt/master/linuxdeployqt.AppDir/linuxdeployqt.svg' \
            -O '${{ env.MAKE_INSTALL_DIR_PATH }}/usr/share/icons/scalable/apps/linuxdeployqt.svg'

      - name: package
        run: |
          pushd '${{ env.PACKAGE_DIR_PATH }}'

          VERSION='0.0.0' \
          '${{ env.LINUXDEPLOYQT_PATH }}' \
            '${{ env.MAKE_INSTALL_DIR_PATH }}/usr/share/applications/qt-screen-HiDPI-test-1.desktop' \
            -appimage \
            -no-translations \
            -verbose=3

          popd

      - name: Upload AppImage
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: "${{ steps.my_luminous_watch.outputs.formattedTime }}_${{ matrix.qt_ver }}_${{ env.APP_NAME }}_AppImage"
          path: "${{ env.PACKAGE_DIR_PATH }}/*.AppImage"
